In [64]:
!pip install seaborn

Requirement already satisfied: seaborn in D:\Career\Python\Lib\site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in D:\Career\Python\Lib\site-packages (from seaborn) (2.5.1)
Requirement already satisfied: pandas>=1.2 in D:\Career\Python\Lib\site-packages (from seaborn) (3.0.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in D:\Career\Python\Lib\site-packages (from seaborn) (3.11.1)
Requirement already satisfied: contourpy>=1.0.1 in D:\Career\Python\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in D:\Career\Python\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in D:\Career\Python\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in D:\Career\Python\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.5.0)
Requirement already satisfied: packaging>=20.0 in D:\Career\Python\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (25.0)
Requirement already satisfied: pillow>=9 in D:\Career\Python\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.3.0)
Requirement already satisfied: pyparsing>=3 in D:\Career\Python\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in D:\Career\Python\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: tzdata in D:\Career\Python\Lib\site-packages (from pandas>=1.2->seaborn) (2025.3)
Requirement already satisfied: six>=1.5 in D:\Career\Python\Lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)

In [78]:
import pandas as pd

fake_titanic = pd.DataFrame({
    "pclass": [3,1,2,3,1,2,3,1,2,3,1,2,3,1,2,3,1,2,3,1],
    "age":    [22,38,26,35,28,54,2,27,14,45,30,19,50,41,33,8,60,25,17,36],
    "fare":   [7.25,71.28,13.00,8.05,53.10,26.55,21.07,80.00,30.07,15.50,
               90.00,12.35,45.50,75.25,29.00,18.75,120.00,35.00,10.50,55.75],
    "actual_survived": [0,1,1,0,1,0,1,0,1,0,1,0,1,0,1,1,0,1,0,1]
})

print(fake_titanic)

    pclass  age    fare  actual_survived
0        3   22    7.25                0
1        1   38   71.28                1
2        2   26   13.00                1
3        3   35    8.05                0
4        1   28   53.10                1
5        2   54   26.55                0
6        3    2   21.07                1
7        1   27   80.00                0
8        2   14   30.07                1
9        3   45   15.50                0
10       1   30   90.00                1
11       2   19   12.35                0
12       3   50   45.50                1
13       1   41   75.25                0
14       2   33   29.00                1
15       3    8   18.75                1
16       1   60  120.00                0
17       2   25   35.00                1
18       3   17   10.50                0
19       1   36   55.75                1

In [79]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
import seaborn as sns

titanic = sns.load_dataset("titanic")

titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [80]:
titanic.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [81]:
titanic[titanic['fare'] == 28.5000]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
331,0,1,male,45.5,0,0,28.5,S,First,man,True,C,Southampton,no,True

In [82]:

X = titanic[["pclass", "age", "fare"]]

y = titanic["survived"]

X["age"] = X["age"].fillna(X["age"].median())

In [83]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [84]:
best_depth = None
least_gap = float('inf')
for depth in [1, 2, 3, None]:
    model = RandomForestClassifier(n_estimators=300,max_depth = depth, random_state = 42)
    model.fit(X_train, y_train)
    train = model.score(X_train, y_train) 
    test = model.score(X_test, y_test)
    gap = abs(train - test)
    print(train, test)
    if gap < least_gap:
        least_gap = gap
        best_depth = depth
        best_train = train
        best_test = test
print(f"best depth is = {best_depth},least gap is = {least_gap}")

0.6853932584269663 0.6312849162011173
0.7219101123595506 0.6759776536312849
0.7275280898876404 0.7039106145251397
0.952247191011236 0.7094972067039106
best depth is = 3,least gap is = 0.023617475362500695

In [97]:
X_test = fake_titanic[['pclass', 'age', 'fare']]

predictions = model.predict(X_test)

fake_titanic['predicted_survived'] = predictions

print(fake_titanic)
fake_titanic["actual_survived"].value_counts()

    pclass  age    fare  actual_survived  predicted_survived
0        3   22    7.25                0                   0
1        1   38   71.28                1                   1
2        2   26   13.00                1                   0
3        3   35    8.05                0                   0
4        1   28   53.10                1                   1
5        2   54   26.55                0                   0
6        3    2   21.07                1                   0
7        1   27   80.00                0                   1
8        2   14   30.07                1                   1
9        3   45   15.50                0                   0
10       1   30   90.00                1                   1
11       2   19   12.35                0                   0
12       3   50   45.50                1                   0
13       1   41   75.25                0                   1
14       2   33   29.00                1                   1
15       3    8   18.75                1                   0
16       1   60  120.00                0                   1
17       2   25   35.00                1                   0
18       3   17   10.50                0                   0
19       1   36   55.75                1                   1

actual_survived
1    11
0     9
Name: count, dtype: int64

In [87]:
X

     pclass   age     fare
0         3  22.0   7.2500
1         1  38.0  71.2833
2         3  26.0   7.9250
3         1  35.0  53.1000
4         3  35.0   8.0500
..      ...   ...      ...
886       2  27.0  13.0000
887       1  19.0  30.0000
888       3  28.0  23.4500
889       1  26.0  30.0000
890       3  32.0   7.7500

[891 rows x 3 columns]

In [98]:
survivors = (predictions == 1).sum()
non_survivors = (predictions == 0).sum()

print("Predicted Survivors:", survivors)
print("Predicted Non-Survivors:", non_survivors)

Predicted Survivors: 9
Predicted Non-Survivors: 11

In [99]:
print(model.feature_names_in_)

['pclass' 'age' 'fare']