In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

In [9]:
df = pd.read_csv("/Users/kbshal/Downloads/kali_mati_tarkari.csv")

In [10]:
df

         Tomato Big(Nepali)    1/5/2021  Kg        50        60        55
0        Tomato Big(Indian)    1/5/2021  Kg        50        60        55
1       Tomato Small(Local)    1/5/2021  Kg        30        35      32.5
2      Tomato Small(Tunnel)    1/5/2021  Kg        30        35      32.5
3      Tomato Small(Indian)    1/5/2021  KG        40        45      42.5
4       Tomato Small(Terai)    1/5/2021  KG        40        45      42.5
...                     ...         ...  ..       ...       ...       ...
96474  Tomato Small(Indian)  2023-09-28  KG  Rs 45.00  Rs 55.00  Rs 50.00
96475   Tomato Small(Local)  2023-09-28  KG  Rs 50.00  Rs 60.00  Rs 55.00
96476  Tomato Small(Tunnel)  2023-09-28  KG  Rs 60.00  Rs 75.00  Rs 69.00
96477              Turnip A  2023-09-28  KG  Rs 70.00  Rs 80.00  Rs 75.00
96478    Water Melon(Green)  2023-09-28  KG  Rs 50.00  Rs 60.00  Rs 56.67

[96479 rows x 6 columns]

In [11]:
df.describe()

       Tomato Big(Nepali)    1/5/2021     Kg        50     60     55
count               96479       96479  96479     96479  96479  96479
unique                133         991      6       268    276   1093
top       Coriander Green  2023-03-14     KG  Rs 50.00     60     55
freq                  991         115  55421      4364   4271   4151

In [14]:
df['Tomato Big(Nepali)'].unique()

array(['Tomato Big(Indian)', 'Tomato Small(Local)',
       'Tomato Small(Tunnel)', 'Tomato Small(Indian)',
       'Tomato Small(Terai)', 'Potato Red', 'Potato Red(Indian)',
       'Potato White', 'Onion Dry (Indian)', 'Carrot(Local)',
       'Carrot(Terai)', 'Cabbage(Local)', 'Cabbage(Terai)', 'Cabbage',
       'Cauli Local', 'Cauli Local(Jyapu)', 'Cauli Terai', 'Raddish Red',
       'Raddish White(Local)', 'Raddish White(Hybrid)', 'Brinjal Long',
       'Brinjal Round', 'Green Peas', 'French Bean(Local)',
       'French Bean(Hybrid)', 'Sword Bean', 'Bitter Gourd',
       'Bottle Gourd', 'Pumpkin', 'Squash(Long)', 'Squash(Round)',
       'Turnip', 'Okara', 'Sweet Potato', 'Barela', 'Arum',
       'Christophine', 'Brd Leaf Mustard', 'Spinach Leaf', 'Cress Leaf',
       'Mustard Leaf', 'Fenugreek Leaf', 'Onion Green', 'Bakula', 'Yam',
       'Mushroom(Kanya)', 'Mushroom(Button)', 'Brocauli', 'Sugarbeet',
       'Red Cabbbage', 'Lettuce', 'Knolkhol', 'Celery', 'Parseley',
       'Fennel Leaf', 'Mint', 'Turnip A', 'Tamarind', 'Bamboo Shoot',
       'Tofu', 'Gundruk', 'Apple(Jholey)', 'Apple(Fuji)', 'Banana',
       'Lime', 'Pomegranate', 'Grapes(Green)', 'Grapes(Black)',
       'Orange(Nepali)', 'Orange(Indian)', 'Water Melon(Green)',
       'Sweet Orange', 'Pineapple', 'Cucumber(Local)', 'Cucumber(Hybrid)',
       'Pear(Chinese)', 'Papaya(Indian)', 'Guava', 'Mombin', 'Kinnow',
       'Strawberry', 'Kiwi', 'Ginger', 'Chilli Dry', 'Chilli Green',
       'Chilli Green(Bullet)', 'Chilli Green(Machhe)', 'Capsicum',
       'Garlic Green', 'Coriander Green', 'Garlic Dry Chinese',
       'Fish Fresh(Rahu)', 'Fish Fresh(Bachuwa)', 'Fish Fresh(Chhadi)',
       'Fish Fresh(Mungari)', 'Tomato Big(Nepali)',
       'Chilli Green(Akbare)', 'Papaya(Nepali)', 'Pointed Gourd(Terai)',
       'Jack Fruit', 'Lemon', 'Pointed Gourd(Local)', 'Drumstick',
       'Smooth Gourd', 'Garlic Dry Nepali', 'Asparagus', 'Sugarcane',
       'French Bean(Rajma)', 'Neuro', 'Clive Green', 'Bauhania flower',
       'Cow pea(Long)', 'Sponge Gourd', 'Clive Dry', 'Snake Gourd',
       'Mango(Calcutte)', 'Water Melon(Dotted)', 'Mango(Maldah)',
       'Cowpea(Short)', 'Soyabean Green', 'Mango(Chousa)',
       'Mango(Dushari)', 'Litchi(Indian)', 'Potato Red(Mude)',
       'Litchi(Local)', 'Pear(Local)', 'Sarifa', 'Avocado', 'Amla',
       'Sweet Lime', 'Mandarin', 'Onion Dry (Chinese)', 'Tree Tomato'],
      dtype=object)